.TH MARK-SHOT-WINDOW-DETECTION-HYPRLAND 1 "August 2026" "Mark Shot 0.1.49" "User Commands"
.SH NAME
mark-shot-window-detection-hyprland \- report Hyprland window geometry to Mark Shot
.SH SYNOPSIS
.B mark-shot-window-detection-hyprland
.SH DESCRIPTION
Queries Hyprland through \fBhyprctl\fR and prints visible window geometry as
JSON. This internal compositor adapter is normally started automatically.
.SH SEE ALSO
.BR mark-shot (1),
.BR hyprctl (1)
