.TH MARK-SHOT-WINDOW-DETECTION-GNOME 1 "August 2026" "Mark Shot 0.1.49" "User Commands"
.SH NAME
mark-shot-window-detection-gnome \- report GNOME window geometry to Mark Shot
.SH SYNOPSIS
.B mark-shot-window-detection-gnome
.SH DESCRIPTION
Queries the bundled GNOME Shell helper extension over D-Bus and prints visible
window geometry as JSON. This internal adapter is normally started
automatically and requires the extension to be enabled for the current user.
.SH SEE ALSO
.BR mark-shot (1),
.BR gdbus (1)
