.TH MARK-SHOT-WINDOW-DETECTION-NIRI 1 "August 2026" "Mark Shot 0.1.49" "User Commands"
.SH NAME
mark-shot-window-detection-niri \- report niri window geometry to Mark Shot
.SH SYNOPSIS
.B mark-shot-window-detection-niri
.SH DESCRIPTION
Queries the niri compositor and prints visible window geometry as JSON. This is
an internal Mark Shot compositor adapter and is normally started automatically.
.SH SEE ALSO
.BR mark-shot (1),
.BR niri (1)
