set(MARK_SHOT_SETTINGS_SOURCES
    src/settings/cloud_translate_settings.cpp
    src/settings/cloud_translate_settings.h
    src/settings/provider_preference_config.cpp
    src/settings/provider_preference_config.h
    src/settings/settings_config.cpp
    src/settings/settings_config.h
    src/settings/settings_config_read.cpp
    src/settings/settings_config_write.cpp
    src/settings/settings_cloud_translate_card.cpp
    src/settings/settings_cloud_translate_card.h
    src/settings/settings_design_tokens.cpp
    src/settings/settings_design_tokens.h
    src/settings/settings_dialog.cpp
    src/settings/settings_dialog.h
    src/settings/settings_navigation.cpp
    src/settings/settings_navigation.h
    src/settings/settings_page_about.cpp
    src/settings/settings_page_about.h
    src/settings/settings_page_advanced.cpp
    src/settings/settings_page_advanced.h
    src/settings/settings_page_annotation.cpp
    src/settings/settings_page_annotation.h
    src/settings/settings_page_capture.cpp
    src/settings/settings_page_capture.h
    src/settings/settings_page_general.cpp
    src/settings/settings_page_general.h
    src/settings/settings_page_integrations.cpp
    src/settings/settings_page_integrations.h
    src/settings/settings_page_pinned.cpp
    src/settings/settings_page_pinned.h
    src/settings/settings_page_plugins.cpp
    src/settings/settings_page_plugins.h
    src/settings/settings_page_plugins_market.cpp
    src/settings/settings_page_plugins_model.cpp
    src/settings/settings_page_plugins_model.h
    src/settings/settings_page_scroll.cpp
    src/settings/settings_page_scroll.h
    src/settings/settings_page_shortcuts.cpp
    src/settings/settings_page_shortcuts.h
    src/settings/settings_page_storage.cpp
    src/settings/settings_page_storage.h
    src/settings/settings_ui_helpers.cpp
    src/settings/settings_ui_helpers.h
    src/settings/settings_wheel_guard.cpp
    src/settings/settings_wheel_guard.h
)
