set(MARK_SHOT_WINDOW_SOURCES
    src/annotation_state_store.cpp
    src/annotation_state_store.h
    src/ocr_result_window.cpp
    src/ocr_result_window.h
    src/ocr_result_window_geometry.cpp
    src/ocr_result_window_geometry.h
    src/ocr_result_window_translation.cpp
    src/shot_window.cpp
    src/shot_window.h
    src/shot_window_actions.cpp
    src/shot_window_annotation_editing.cpp
    src/shot_window_annotation_painting.cpp
    src/shot_window_arrow_rendering.cpp
    src/shot_window_canvas.cpp
    src/shot_window_code_scan.cpp
    src/shot_window_code_scan_result_window.cpp
    src/shot_window_config.cpp
    src/shot_window_display_capture.cpp
    src/shot_window_double_click_action.cpp
    src/shot_window_hit_testing.cpp
    src/shot_window_input.cpp
    src/shot_window_input_shortcuts.cpp
    src/shot_window_internal.cpp
    src/shot_window_internal.h
    src/shot_window_layout.cpp
    src/shot_window_lifecycle.cpp
    src/shot_window_line_anchors.cpp
    src/shot_window_line_constraint.cpp
    src/shot_window_line_constraint.h
    src/shot_window_magnifier_drag.cpp
    src/shot_window_modes.cpp
    src/shot_window_module.h
    src/shot_window_ocr_result_window.cpp
    src/shot_window_overlay_panels.cpp
    src/shot_window_pinned_window.cpp
    src/shot_window_property_panels.cpp
    src/shot_window_qt_fwd.h
    src/selection_cursor_nudge.cpp
    src/selection_cursor_nudge.h
    src/selection_loupe.cpp
    src/selection_loupe.h
    src/shot_window_selection_frame.cpp
    src/shot_window_selection_repaint.cpp
    src/shot_window_setup.cpp
    src/shot_window_shortcut_registration.cpp
    src/shot_window_shortcuts.cpp
    src/shot_window_side_panels.cpp
    src/shot_window_startup_color_dialog.cpp
    src/shot_window_state.cpp
    src/shot_window_text_controls.cpp
    src/shot_window_text_editor.cpp
    src/shot_window_text_layout.cpp
    src/shot_window_upload.cpp
    src/shot_window_width_state.cpp
    src/window_hover_selection.cpp
    src/window_hover_selection.h
)
